-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 10:57:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema series_whiched
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema series_whiched
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `series_whiched` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- This schema was created for a stub table

-- -----------------------------------------------------
-- Schema mydb
--
-- This schema was created for a stub table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `series_whiched` ;

-- -----------------------------------------------------
-- Table `series_whiched`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `series_whiched`.`serie` ;

CREATE TABLE IF NOT EXISTS `series_whiched`.`serie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_whiched`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `series_whiched`.`user` ;

CREATE TABLE IF NOT EXISTS `series_whiched`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_whiched`.`user_serie_assisti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel_api_series`.`users_series` ;

CREATE TABLE IF NOT EXISTS `laravel_api_series`.`user_serie_assisti` (
  `user_id` INT NOT NULL,
  `serie_id` INT NOT NULL,
  `type` ENUM('watched', 'watchlist') NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `seried_id_idx` (`serie_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `serie_id`, `type`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `series_whiched`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `seried_id`
    FOREIGN KEY (`serie_id`)
    REFERENCES `series_whiched`.`serie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb` ;
USE `series_whiched` ;

-- -----------------------------------------------------
-- Placeholder table for view `series_whiched`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_whiched`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `series_whiched`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `series_whiched`.`view1`;
DROP VIEW IF EXISTS `series_whiched`.`view1` ;
USE `series_whiched`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
